"""Update Program model

Revision ID: 38a3907467eb
Revises: dfead6547dfb
Create Date: 2026-06-19 13:07:55.720765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a3907467eb'
down_revision = 'dfead6547dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('admin_id')
        batch_op.drop_column('status')
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###
