"""Add program interests model and added slag and featured in program model

Revision ID: 5c574cafee5a
Revises: 38a3907467eb
Create Date: 2026-06-25 15:25:43.009196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c574cafee5a'
down_revision = '38a3907467eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint("uq_program_slug", ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('featured')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
